on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: webhook
        env:
          WEBHOOK: ${{ secrets.BLOG_BUILD_WEBHOOK }}
        run: curl -X POST $WEBHOOK
