on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go run ./cmd/blog-rebuild
