on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: webhook
        run: curl -X GET https://api.sorcererxw.com/job/refresh_jike_rss
